---
title: "Reading_data_from_web"
output: html_document
---

```{r}
library(tidyverse)
library(rvest)
library(httr)
```

#Extracting Tables
```{r}
url1 = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"
drug_use_xml = read_html(url1)

```

CSS selector
```{r}
table_marj = drug_use_xml %>% 
  html_nodes(css = "table") %>% 
  .[[1]] %>% 
  html_table() %>% 
  slice(-1) %>% 
  as.tibble() 

```

##Assignment1
```{r}
nyc_cost = read_html("https://www.bestplaces.net/cost_of_living/city/new_york/new_york") %>% 
  html_nodes(css = "table") %>% 
  .[[1]] %>% 
  html_table(header = TRUE)
```

##CSS Selectors
```{r}
hpsaga = read_html("https://www.imdb.com/list/ls000630791/")

title = hpsaga %>% 
  html_nodes(".lister-item-header a") %>% 
  html_text()

comments = hpsaga %>% 
  html_nodes(".ipl-rating-star.small .ipl-rating-star__rating") %>% 
  html_text()

gross = hpsaga %>% 
  html_nodes(".text-muted .ghost~ .text-muted+ span") %>% 
  html_text()

votes = hpsaga %>% 
  html_nodes(".text-muted+ span:nth-child(2)") %>% 
  html_text() %>% 
  .[-1:-3]
hp_inf = tibble(
  title = title,
  comments = comments,
  gross = gross,
  votes = votes
)

```

```{r}
amazon = read_html("https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber=1")

statements = amazon %>% 
  html_nodes("#cm_cr-review_list .a-color-base") %>% 
  html_text()

star = amazon %>% 
  html_nodes("#cm_cr-review_list .review-rating") %>% 
html_text()

amazon = tibble(
  title = statements,
  star = star
)
```
#Using API









